<?php
/**
 * @var \Villermen\Toolbox\App $this
 * @var string|null $icon
 * @var string|null $title
 * @var string|null $subtitle
 * @var string|null $head
 * @var string|string[]|null $script
 */
$icon = ($icon ?? null);
$title = ($title ?? null);
$subtitle = ($subtitle ?? null);
$head = ($head ?? null);
$script = ($script ?? []);
$script = is_string($script) ? [$script] : $script;

$profile = $this->getAuthenticatedProfile();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $title !== 'Toolbox' ? sprintf('%s - ', $title) : ''; ?>Toolbox</title>
        <link rel="stylesheet" href="<?= $this->createPath('style.css'); ?>" />
        <link rel="icon" href="<?= $this->createPath('toolbox-square.png'); ?>" />
        <?php if ($head): ?>
            <?= $head; ?>
        <?php endif; ?>
        <?php foreach ($script as $src): ?>
            <script src="<?= $src; ?>" defer></script>
        <?php endforeach; ?>
    </head>
    <body>
        <div class="container mt-5 mb-5">
            <?php foreach($this->popFlashMessages() as $flashMessage): ?>
                <div class="<?= sprintf('alert alert-dismissible alert-%s fade show', $flashMessage['color']); ?>">
                    <?= htmlspecialchars($flashMessage['message']); ?>
                    <button type="button" class="btn btn-sm btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                </div>
            <?php endforeach; ?>
            <div class="clearfix">
                <?php if ($profile): ?>
                    <img
                            class="border border-dark rounded-circle float-end align-middle"
                            style="height: 42px;"
                            src="<?= htmlspecialchars($profile->getAvatar()); ?>"
                            alt="<?= htmlspecialchars($profile->getName()); ?>"
                    />
                <?php endif; ?>
                <h1 class="d-inline-block me-3 mb-0">
                    <?php if ($icon): ?>
                        <img src="<?= $icon; ?>" alt="" class="align-baseline" style="height: 27px;" />
                    <?php endif; ?>
                    <?= $title; ?>
                </h1>
                <div class="lead d-inline-block"><?= $subtitle; ?></div>
            </div>
            <hr />
